name: Danger Notion Sync

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]

jobs:
    danger:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - run: npm install danger @notionhq/client
            - run: npx danger ci
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
                NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
