name: Sync GitHub Issues to Notion

on:
  issues:
    types: [opened, edited, reopened, closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install @notionhq/client
      - run: node sync-issue.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          ISSUE_TITLE: "${{ github.event.issue.title }}"
          ISSUE_URL: "${{ github.event.issue.html_url }}"
          ISSUE_STATE: "${{ github.event.issue.state }}"
          ISSUE_LABELS: "${{ toJson(github.event.issue.labels) }}"
          REPO_NAME: "${{ github.repository }}"
